apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: query-forge-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "4000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: auth
          image: mathieuvss/auth-service:latest
          ports:
            - containerPort: 4000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 5
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_PORT
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: JWT_SECRET
            - name: JWT_EXPIRES_IN
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: JWT_EXPIRES_IN
            - name: REFRESH_TOKEN_EXPIRES_IN
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REFRESH_TOKEN_EXPIRES_IN
            - name: AUTH_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: AUTH_PORT
            - name: EMAIL_USER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: EMAIL_USER
            - name: EMAIL_PASS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: EMAIL_PASS
            - name: FRONTEND_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: FRONTEND_HOST
            - name: NEST_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: NEST_BASE_URL_LOCAL

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: query-forge-dev
  labels:
    app: auth
spec:
  selector:
    app: auth
  ports:
    - port: 4000
      targetPort: 4000
