apiVersion: apps/v1
kind: Deployment
metadata:
  name: sync
  namespace: query-forge-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sync
  template:
    metadata:
      labels:
        app: sync
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3333"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: sync
          image: mathieuvss/sync-service:latest
          ports:
            - containerPort: 3333
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_PORT
            - name: ELASTICSEARCH_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ELASTICSEARCH_HOSTS
            - name: YOUTUBE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: YOUTUBE_API_KEY
            - name: APIFY_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: APIFY_API_TOKEN
            - name: SCRAPER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SCRAPER_SERVICE_URL
            - name: SYNC_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SYNC_PORT
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3333
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 3333
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: sync-service
  namespace: query-forge-dev
  labels:
    app: sync
spec:
  selector:
    app: sync
    ports:
      - port: 3333
        targetPort: 3333
