services:
  sync-service:
    build:
      context: ./backend/sync-service
      dockerfile: Dockerfile
    container_name: sync-service-query-forge-dev
    volumes:
      - ./backend/sync-service/src:/app/src
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOSTS}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - APIFY_API_TOKEN=${APIFY_API_TOKEN}

    restart: unless-stopped
