apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  namespace: query-forge-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
        - name: adminer
          image: adminer:5.3.0
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"

---
apiVersion: v1
kind: Service
metadata:
  name: adminer-service
  namespace: query-forge-dev
  labels:
    app: adminer
spec:
  selector:
    app: adminer
  ports:
    - port: 8080
      targetPort: 8080
