apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-secret
  namespace: cert-manager
type: Opaque
data:
  CF_API_EMAIL: bG8uZ2F1dGhpZXIuZ2xvQGdtYWlsLmNvbQ==
  CF_API_KEY: RGhQODZCeUVjTzVtOE83c0RNMjhsMzVBVkhfajlrYnlHLVZoRE8tQg==

---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-auth
  namespace: query-forge-dev
type: Opaque
data:
  auth: YWRtaW46JGFwcjEkSDY1dzc0LS4kSWFhNzl4bDYuTVdqZndlQ2kyUzlmLg==