apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-secret
  namespace: kube-system
type: Opaque
data:
  CF_API_EMAIL: bG8uZ2F1dGhpZXIuZ2xvQGdtYWlsLmNvbQ==
  CF_API_KEY: RGhQODZCeUVjTzVtOE83c0RNMjhsMzVBVkhfajlrYnlHLVZoRE8tQg==
