apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service-external
  namespace: query-forge-dev
spec:
  type: ClusterIP
  ports:
    - port: 9200
      targetPort: 9200
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: elasticsearch-service-external
  namespace: query-forge-dev
subsets:
  - addresses:
      - ip: 192.168.1.144 # TODO: change to host from lxc elasticsearch
    ports:
      - port: 9200
        protocol: TCP
