apiVersion: v1
kind: Service
metadata:
  name: postgres-service-external
  namespace: query-forge-dev
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: postgres-service-external
  namespace: query-forge-dev
subsets:
  - addresses:
      - ip: 192.168.1.142 # TODO: change to host from lxc postgres
    ports:
      - port: 5432
        protocol: TCP
