FROM node:23-alpine

WORKDIR /app

COPY package*.json ./

RUN npm ci --include=dev

COPY . .

RUN npm run build

RUN chmod +x entrypoint.sh
RUN chmod +x entrypoint.prod.sh

EXPOSE 3000

CMD ["/bin/sh", "./entrypoint.sh"] 