apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    # Configuration pour K3S avec Cloudflare
    additionalArguments:
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.cloudflare.acme.email=lo.gauthier.glo@gmail.com"
      - "--certificatesresolvers.cloudflare.acme.storage=/data/acme.json"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.delaybeforecheck=10s"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.addEntryPointsLabels=true"
      - "--metrics.prometheus.addServicesLabels=true"
      - "--api.dashboard=true"
      - "--api.insecure=false"

    # Variables d'environnement pour Cloudflare
    env:
      - name: CF_API_EMAIL
        valueFrom:
          secretKeyRef:
            name: cloudflare-secret
            key: CF_API_EMAIL
      - name: CF_API_KEY
        valueFrom:
          secretKeyRef:
            name: cloudflare-secret
            key: CF_API_KEY

    # Configuration des ports
    ports:
      web:
        port: 80
        expose: true
        exposedPort: 80
        protocol: TCP
      websecure:
        port: 443
        expose: true
        exposedPort: 443
        protocol: TCP
        tls:
          enabled: true
      traefik:
        port: 9000
        expose: false
        protocol: TCP

    # Volumes pour ACME
    persistence:
      enabled: true
      path: /data
      size: 128Mi
      storageClass: "local-path"

    # Service pour LoadBalancer
    service:
      type: LoadBalancer
