apiVersion: v1
kind: Service
metadata:
  name: traefik-service-metrics
  namespace: kube-system
  labels:
    app: traefik
spec:
  selector:
    app: traefik
  ports:
    - name: metrics
      port: 9100
      targetPort: 9100
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: traefik-service-dashboard
  namespace: kube-system
  labels:
    app: traefik
spec:
  selector:
    app: traefik
  ports:
    - name: dashboard
      port: 8080
      targetPort: 8080
  type: ClusterIP
